apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} #eshop
  labels:
    app: "{{ template "name" . }}" #eshop
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
  selector:
    matchLabels:
        app: "{{ template "name" . }}" #eshop
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}" #eshop
    spec:
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}" #eshop
          imagePullPolicy: Always
          name: "{{ template "name" . }}" #eshop
          ports:
            - containerPort: 80
