apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop
  labels:
    app: eshop
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
  selector:
    matchLabels:
        app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - image: eshop
          imagePullPolicy: Always
          name: eshop
          ports:
            - containerPort: 80
