version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EShopDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  eshop:
    depends_on:
      - postgres
    image: eshop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - eshop

  grafana:
    image: grafana/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus
  
volumes:
    pgdata:
    grafana_storage:

